# Generated by Django 6.1 on 2026-08-06 23:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('external_id', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('external_ids', models.JSONField(db_default={})),
                ('hired_at', models.DateField(blank=True, null=True)),
                ('dismissed_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Payrun',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('period', models.DateField()),
                ('status', core.fields.EnumField(db_default='draft', db_type_name='payrun_status')),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payruns',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('country_code', models.TextField()),
                ('base_currency', models.TextField()),
                ('report_currency', models.TextField(db_default='EUR')),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('country_code', models.TextField()),
                ('period', models.DateField()),
                ('norm_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('working_days', models.IntegerField()),
                ('holidays', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), db_default=[])),
            ],
            options={
                'db_table': 'calendars',
                'constraints': [models.UniqueConstraint(fields=('country_code', 'period'), name='calendars_country_period_uniq')],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('base_currency', models.TextField()),
                ('quote_currency', models.TextField()),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
            options={
                'db_table': 'fx_rates',
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'rate_date'), name='fx_rates_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('net', models.DecimalField(db_default=0, decimal_places=2, max_digits=14)),
                ('gross', models.DecimalField(db_default=0, decimal_places=2, max_digits=14)),
                ('tax', models.DecimalField(db_default=0, decimal_places=2, max_digits=14)),
                ('contributions', models.DecimalField(db_default=0, decimal_places=2, max_digits=14)),
                ('total_cost', models.DecimalField(db_default=0, decimal_places=2, max_digits=14)),
                ('to_bank', models.DecimalField(db_default=0, decimal_places=2, max_digits=14)),
                ('to_cash', models.DecimalField(db_default=0, decimal_places=2, max_digits=14)),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_default=[])),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('payrun', models.ForeignKey(db_column='payrun_id', on_delete=django.db.models.deletion.CASCADE, to='core.payrun')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'payslips',
            },
        ),
        migrations.CreateModel(
            name='PnlItem',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('kind', models.TextField()),
                ('sort_order', models.IntegerField(db_default=0)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pnlitem')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'pnl_items',
            },
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('scheme', models.TextField()),
                ('ledger', core.fields.EnumField(db_default='official', db_type_name='ledger')),
                ('pnl_item', models.ForeignKey(blank=True, db_column='pnl_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pnlitem')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'employee_groups',
            },
        ),
        migrations.CreateModel(
            name='RulePreset',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('country_code', models.TextField()),
                ('body', models.JSONField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule_presets',
                'constraints': [models.UniqueConstraint(fields=('code', 'valid_from'), name='rule_presets_code_valid_from_uniq')],
            },
        ),
        migrations.AddField(
            model_name='payrun',
            name='preset',
            field=models.ForeignKey(blank=True, db_column='preset_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rulepreset'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('permissions', models.JSONField(db_default=[])),
                ('visible_ledgers', django.contrib.postgres.fields.ArrayField(base_field=core.fields.EnumField(db_type_name='ledger'), db_default=['official'])),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('period', models.DateField()),
                ('status', core.fields.EnumField(db_default='open', db_type_name='period_status')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'periods',
            },
        ),
        migrations.AddField(
            model_name='payrun',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='PayComponent',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ledger', core.fields.EnumField(db_type_name='ledger')),
                ('channel', core.fields.EnumField(db_default='bank', db_type_name='payout_channel')),
                ('taxable', models.BooleanField(db_default=True)),
                ('payslip', models.ForeignKey(db_column='payslip_id', on_delete=django.db.models.deletion.CASCADE, to='core.payslip')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'pay_components',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('unit_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='core.role')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('tax_number', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'legal_entities',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('tax_number', models.TextField(blank=True, null=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_default=[])),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'counterparties',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('external_ids', models.JSONField(db_default={})),
                ('legal_entity', models.ForeignKey(blank=True, db_column='legal_entity_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.legalentity')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('period', models.DateField()),
                ('insured_hours', models.DecimalField(db_default=0, decimal_places=2, max_digits=8)),
                ('norm_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hours', models.JSONField(db_default={})),
                ('deduction', models.DecimalField(db_default=0, decimal_places=2, max_digits=14)),
                ('source', models.TextField(db_default='manual')),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('unit', models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit')),
            ],
            options={
                'db_table': 'timesheets',
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='unit',
            field=models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit'),
        ),
        migrations.CreateModel(
            name='EmploymentTerm',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('base_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('coefficient', models.DecimalField(db_default=1, decimal_places=4, max_digits=8)),
                ('scheme', models.TextField(blank=True, null=True)),
                ('ledger', core.fields.EnumField(blank=True, db_type_name='ledger', null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.PROTECT, to='core.employeegroup')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('unit', models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit')),
            ],
            options={
                'db_table': 'employment_terms',
            },
        ),
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('method', core.fields.EnumField(db_type_name='allocation_method')),
                ('ledger', core.fields.EnumField(db_default='official', db_type_name='ledger')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('counterparty', models.ForeignKey(db_column='counterparty_id', on_delete=django.db.models.deletion.CASCADE, to='core.counterparty')),
                ('pnl_item', models.ForeignKey(db_column='pnl_item_id', on_delete=django.db.models.deletion.PROTECT, to='core.pnlitem')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('unit', models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
            options={
                'db_table': 'allocation_rules',
            },
        ),
        migrations.CreateModel(
            name='RuleOverride',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('scope_type', core.fields.EnumField(db_type_name='rule_scope')),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('path', models.TextField()),
                ('value', models.JSONField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'rule_overrides',
                'indexes': [models.Index(models.F('tenant'), models.F('scope_type'), models.F('scope_id'), models.OrderBy(models.F('valid_from'), descending=True), name='rule_overrides_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='rule_overrides_period_check')],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='roles_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pnlitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='pnl_items_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pnlitem',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['revenue', 'expense', 'subtotal'])), name='pnl_items_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('tenant', 'period'), name='periods_tenant_period_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payrun',
            constraint=models.UniqueConstraint(fields=('tenant', 'period'), name='payruns_tenant_period_uniq'),
        ),
        migrations.AddIndex(
            model_name='paycomponent',
            index=models.Index(models.F('tenant'), models.F('payslip'), name='pay_components_payslip_idx'),
        ),
        migrations.AddIndex(
            model_name='paycomponent',
            index=models.Index(models.F('tenant'), models.F('code'), name='pay_components_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user_id', 'role'), name='memberships_tenant_user_role_uniq'),
        ),
        migrations.AddConstraint(
            model_name='employeegroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='employee_groups_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_id'), name='employees_tenant_external_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='units_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'period', 'unit'), name='timesheets_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('payrun', 'employee'), name='payslips_payrun_employee_uniq'),
        ),
        migrations.AddIndex(
            model_name='employmentterm',
            index=models.Index(models.F('tenant'), models.F('employee'), models.OrderBy(models.F('valid_from'), descending=True), name='employment_terms_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='employmentterm',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='employment_terms_period_check'),
        ),
        migrations.AddIndex(
            model_name='allocationrule',
            index=models.Index(models.F('tenant'), models.F('counterparty'), models.OrderBy(models.F('valid_from'), descending=True), name='allocation_rules_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'fixed_unit'), _negated=True), ('unit__isnull', False), _connector='OR'), name='allocation_rules_fixed_unit_check'),
        ),
        migrations.AddConstraint(
            model_name='allocationrule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='allocation_rules_period_check'),
        ),
    ]
