"""Должности: шаблон условий найма (issue #181).

**Что появляется.** Таблица `positions` — то, из чего собираются условия найма
человека, — и колонка `employment_terms.position_id`, которой связь запоминается.

**Почему должность не то же самое, что группа сотрудников.** Группа отвечает на
вопрос «как считается работа этих людей» — схема расчёта, регистр, чем меряется
труд; она приходит из правил страны и живёт в P&L строкой затрат. Должность
отвечает на вопрос «кого мы нанимаем»: пиццамейкер, курьер, управляющий — с вилкой ставки
и обычными для этой роли значениями. Одной группе законно соответствуют
несколько должностей, и сводить их в одну таблицу значило бы либо раздувать
группы до списка вакансий, либо терять вилку.

**Связь односторонняя и слабая.** Условия найма помнят, из какой должности они
собраны, но дальше живут сами: `on delete set null`. Правка должности не трогает
нанятых — иначе она молча пересчитывала бы закрытые месяцы всем, кто на ней
сидит, а это ровно то, что запрещает версионирование условий (D020).

**Право на ведение — то же `directory.manage`**, что у остальных справочников
(`0130`), и той же формой политик: ограничивающие только на запись. Должности
обязаны видеть все, кто заводит людей и читает карточки, а вести их вправе
администратор сети.
"""

# Generated by Django 6.1 on 2026-08-27 09:24

import django.db.models.deletion
from django.db import migrations, models

import core.fields

# --- комментарии в самой базе -------------------------------------------------
# Схема объясняется тому, кто пришёл в неё psql-ом (соглашение проекта, `0003`).
COMMENTS = """
comment on table positions is
    'Должности партнёра: шаблон условий найма. Подставляют значения, но не диктуют их — условия живут дальше сами';
comment on column positions.code is
    'Код должности, уникальный у партнёра';
comment on column positions.group_id is
    'Группа сотрудников, в которую попадает нанятый на эту должность. Группа отвечает за расчёт, должность — за наём';
comment on column positions.work_measure is
    'Чем меряется работа: пусто — как у группы. То же поле, что человек может переопределить в своих условиях';
comment on column positions.rate_from is
    'Нижняя граница ставки. Пусто — границы нет: у части должностей ставка договорная';
comment on column positions.rate_to is
    'Верхняя граница ставки. Ловит опечатку в момент ввода: 420 вместо 4200 — лишняя цифра, а не низкая ставка';
comment on column employment_terms.position_id is
    'Из какой должности собраны условия. Пусто — набраны руками: должности появились позже';
"""

# --- разграничение доступа ------------------------------------------------------
# Изоляция тенанта — как у всех таблиц с `tenant_id`. Право вести справочник —
# как у остальных (`0130`, `0231`): ограничивающие политики только на запись.
POLICIES = """
alter table positions enable row level security;
alter table positions force  row level security;

create policy tenant_isolation on positions
    for all
    using (tenant_id in (select app_tenant_ids()))
    with check (tenant_id in (select app_tenant_ids()));

create policy directory_manage_insert on positions
    as restrictive for insert
    with check (app_has_permission(tenant_id, 'directory.manage'));

create policy directory_manage_update on positions
    as restrictive for update
    with check (app_has_permission(tenant_id, 'directory.manage'));

create policy directory_manage_delete on positions
    as restrictive for delete
    using (app_has_permission(tenant_id, 'directory.manage'));
"""

DROP_POLICIES = """
drop policy if exists directory_manage_delete on positions;
drop policy if exists directory_manage_update on positions;
drop policy if exists directory_manage_insert on positions;
drop policy if exists tenant_isolation on positions;
alter table positions no force row level security;
alter table positions disable row level security;
"""

# Привилегии роли продукта: без них разграничение выглядело бы работающим, а
# продукт не читал бы ничего.
PRIVILEGES = "grant select, insert, update, delete on positions to app_user;"
DROP_PRIVILEGES = "revoke all on positions from app_user;"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0248_country_rules_in_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('work_measure', models.TextField(blank=True, null=True)),
                ('scheme', models.TextField(blank=True, null=True)),
                ('ledger', core.fields.EnumField(blank=True, db_type_name='ledger', null=True)),
                ('rate_from', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rate_to', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.PROTECT, to='core.employeegroup')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.AddField(
            model_name='employmentterm',
            name='position',
            field=models.ForeignKey(blank=True, db_column='position_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.position'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='positions_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('rate_from__isnull', True), ('rate_to__isnull', True), ('rate_to__gte', models.F('rate_from')), _connector='OR'), name='positions_rate_range'),
        ),
        migrations.RunSQL(COMMENTS, migrations.RunSQL.noop),
        migrations.RunSQL(POLICIES, DROP_POLICIES),
        migrations.RunSQL(PRIVILEGES, DROP_PRIVILEGES),
    ]
