"""Договорные часы: сколько человек обязан отработать (issue #171).

**Что появляется.** Колонка `employment_terms.contract_hours` и такая же у
должности — умолчание, которое подставляется при найме.

**Почему величина у условий найма, а не только у должности.** Она меняется
вместе с условиями: перевели человека на полставки — норма по договору стала
другой с той же даты. Держать её только в должности значило бы, что прошлые
месяцы пересчитываются задним числом при переводе, а это ровно то, что
запрещает версионирование условий (D020).

**Пусто — это значение, а не пропуск.** У части людей договорные часы не
считают вовсе; про них нельзя сказать «недобрал», и в итоге точки они не
участвуют. Ноль здесь означал бы «обязан отработать ноль часов» — то есть
любую отработку показывал бы переработкой.
"""

# Generated by Django 6.1 on 2026-08-27 10:24

from django.db import migrations, models

# --- комментарии в самой базе -------------------------------------------------
COMMENTS = """
comment on column employment_terms.contract_hours is
    'Сколько часов человек обязан отработать по договору. Пусто — величины нет: у части людей её не считают';
comment on column positions.contract_hours is
    'Договорные часы по умолчанию для нанятых на эту должность. Подставляются в условия найма и живут там своей версией';
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentterm',
            name='contract_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='contract_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.RunSQL(COMMENTS, migrations.RunSQL.noop),
    ]
