# Generated by Django 6.1 on 2026-08-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0251_position_without_group_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='position',
            name='positions_rate_range',
        ),
        migrations.RemoveField(
            model_name='position',
            name='rate_from',
        ),
        migrations.RemoveField(
            model_name='position',
            name='rate_to',
        ),
    ]
