"""Отложенные находки проверки полноты (issue #175).

Проверка «прежде чем закрыть» была бы тупиком без этой таблицы: часть находок
законна — выписка придёт послезавтра, а зарплату платят сегодня. Запрет без
выхода заставил бы закрывать месяц мимо продукта, то есть хуже, чем не
проверять вовсе.

Причина обязательна ограничением базы, а не только формой: отложенное без
причины через полгода необъяснимо — видно, что месяц закрыли с дырой, и
неизвестно, сознательно или по недосмотру.

Право то же, что у утверждения периода: откладывает тот, кто закрывает месяц.
"""

# Generated by Django 6.1 on 2026-08-27 20:42

import django.db.models.deletion
from django.db import migrations, models

COMMENTS = """
comment on table closing_waivers is
    'Находки проверки полноты, отложенные с причиной: месяц закрыт, дыра известна и объяснена';
comment on column closing_waivers.finding is
    'Код находки из payrun.readiness: unit_hours, papers, inbox';
comment on column closing_waivers.reason is
    'Почему закрываем, зная о дыре. Обязательна: без причины запись необъяснима через полгода';
"""

POLICIES = """
alter table closing_waivers enable row level security;
alter table closing_waivers force  row level security;

create policy tenant_isolation on closing_waivers
    for all
    using (tenant_id in (select app_tenant_ids()))
    with check (tenant_id in (select app_tenant_ids()));

create policy approve_insert on closing_waivers
    as restrictive for insert
    with check (app_has_permission(tenant_id, 'period.approve'));

create policy approve_delete on closing_waivers
    as restrictive for delete
    using (app_has_permission(tenant_id, 'period.approve'));
"""

DROP_POLICIES = """
drop policy if exists approve_delete on closing_waivers;
drop policy if exists approve_insert on closing_waivers;
drop policy if exists tenant_isolation on closing_waivers;
alter table closing_waivers no force row level security;
alter table closing_waivers disable row level security;
"""

PRIVILEGES = "grant select, insert, update, delete on closing_waivers to app_user;"
DROP_PRIVILEGES = "revoke all on closing_waivers from app_user;"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0252_position_without_rate_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingWaiver',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('period', models.DateField()),
                ('finding', models.TextField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'closing_waivers',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'period', 'finding'), name='closing_waivers_uniq'), models.CheckConstraint(condition=models.Q(('reason__regex', '\\S')), name='closing_waivers_reason_not_empty')],
            },
        ),
        migrations.RunSQL(COMMENTS, migrations.RunSQL.noop),
        migrations.RunSQL(POLICIES, DROP_POLICIES),
        migrations.RunSQL(PRIVILEGES, DROP_PRIVILEGES),
    ]
