"""Протокол сверки с таблицей бухгалтера (issue #172).

Сверка жила до перезагрузки страницы: посчитали, показали, закрыли — и её не
было. Доказать через месяц, что расхождения разобрали, было нечем: у бухгалтера
остаётся её файл, у нас — ничего.

**Файл не хранится и здесь, и это не забывчивость, а D028.** В таблице партнёра
ФИО и суммы живых людей; сверка не повод заводить им ещё одно место жительства.
Протокол хранит результат сравнения: имя файла, счётчики и расхождения со
ссылкой на наших же сотрудников. Новых персональных данных не появляется —
поэтому в таблице нет ни одной колонки под содержимое.

Решение по расхождению — половина смысла: без него протокол отвечает
«разошлось», а вопрос через полгода звучит «и что вы с этим сделали».
Ограничение базы требует объяснения рядом с решением: «ошибка в файле» без слов
через полгода не отличить от «не разбирались».

Право — то же, что у расчёта: сверяет тот, кто ведёт месяц.
"""

# Generated by Django 6.1 on 2026-08-27 21:35

import django.db.models.deletion
from django.db import migrations, models

COMMENTS = """
comment on table reconciliations is
    'Протокол сверки с таблицей бухгалтера: когда, кто, какой файл и чем кончилось. Самого файла здесь нет (D028)';
comment on column reconciliations.file_name is
    'Имя файла, чтобы человек узнал свою сверку в списке. Содержимое не хранится';
comment on table reconciliation_findings is
    'Расхождения сверки и решение человека по каждому: наша сторона, ошибка в файле или разная трактовка правила';
comment on column reconciliation_findings.employee_id is
    'Наш сотрудник, а не имя из файла: ФИО в протокол не переезжают';
"""

POLICIES = """
alter table reconciliations enable row level security;
alter table reconciliations force  row level security;
alter table reconciliation_findings enable row level security;
alter table reconciliation_findings force  row level security;

create policy tenant_isolation on reconciliations
    for all
    using (tenant_id in (select app_tenant_ids()))
    with check (tenant_id in (select app_tenant_ids()));

create policy calculate_insert on reconciliations
    as restrictive for insert
    with check (app_has_permission(tenant_id, 'payrun.calculate'));

create policy tenant_isolation on reconciliation_findings
    for all
    using (tenant_id in (select app_tenant_ids()))
    with check (tenant_id in (select app_tenant_ids()));

create policy calculate_write on reconciliation_findings
    as restrictive for insert
    with check (app_has_permission(tenant_id, 'payrun.calculate'));

create policy calculate_update on reconciliation_findings
    as restrictive for update
    with check (app_has_permission(tenant_id, 'payrun.calculate'));
"""

DROP_POLICIES = """
drop policy if exists calculate_update on reconciliation_findings;
drop policy if exists calculate_write on reconciliation_findings;
drop policy if exists tenant_isolation on reconciliation_findings;
drop policy if exists calculate_insert on reconciliations;
drop policy if exists tenant_isolation on reconciliations;
alter table reconciliation_findings no force row level security;
alter table reconciliation_findings disable row level security;
alter table reconciliations no force row level security;
alter table reconciliations disable row level security;
"""

PRIVILEGES = """
grant select, insert, update, delete on reconciliations to app_user;
grant select, insert, update, delete on reconciliation_findings to app_user;
"""
DROP_PRIVILEGES = """
revoke all on reconciliation_findings from app_user;
revoke all on reconciliations from app_user;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0253_closing_waivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('period', models.DateField()),
                ('file_name', models.TextField()),
                ('lines', models.IntegerField(db_default=0)),
                ('matched', models.IntegerField(db_default=0)),
                ('rounding', models.IntegerField(db_default=0)),
                ('differing', models.IntegerField(db_default=0)),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'reconciliations',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationFinding',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('component', models.TextField()),
                ('ours', models.DecimalField(decimal_places=2, max_digits=14)),
                ('theirs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('decision', models.TextField(blank=True, null=True)),
                ('note', models.TextField(db_default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('record', models.ForeignKey(db_column='reconciliation_id', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.reconciliation')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'reconciliation_findings',
            },
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(models.F('tenant'), models.F('period'), models.OrderBy(models.F('created_at'), descending=True), name='reconciliations_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationfinding',
            constraint=models.CheckConstraint(condition=models.Q(('decision__isnull', True), ('note__regex', '\\S'), _connector='OR'), name='reconciliation_findings_note_with_decision'),
        ),
        migrations.RunSQL(COMMENTS, migrations.RunSQL.noop),
        migrations.RunSQL(POLICIES, DROP_POLICIES),
        migrations.RunSQL(PRIVILEGES, DROP_PRIVILEGES),
    ]
