"""Память разбора инбокса: что человек уже решал по этому поставщику (issue #173).

Половина инбокса каждый месяц — одни и те же поставщики. Пока продукт ничего не
помнит, бухгалтер выбирает ту же статью из выпадающего списка сорок раз подряд;
на сороковом он уже не читает, что нажимает. Эталон (модуль 3) ставит цель
прямо: «разобрать сорок штук за десять минут — это цель, а не метафора».

Таблица помнит ровно одно соответствие — поставщик → статья, — и никогда не
ставит его сама. Автоматическая простановка это уже распознавание: назначенная
молча статья уезжает в P&L, и находят её на сверке.

Право на запись — то же, что на разбор первички: помнит система за тем, кто
разбирает. Управляющий точки правил не заводит: его дело донести бумагу.
"""

# Generated by Django 6.1 on 2026-08-28 00:20

import django.db.models.deletion
from django.db import migrations, models

# Внешние ключи ставятся здесь, а не Django (`db_constraint=False` в модели), —
# ради `on delete cascade` **в самой базе**. Django исполняет каскад в Python и
# до чистого SQL не дотягивается; без каскада запомненное решение держит
# контрагента и статью, то есть справочник нельзя ни почистить, ни поправить,
# пока не разобран инбокс. Память о выборе не должна стоить так дорого:
# контрагента убрали — помнить про него нечего.
KEYS = """
alter table classification_rules
    add constraint classification_rules_counterparty_fkey
        foreign key (counterparty_id) references counterparties (id) on delete cascade,
    add constraint classification_rules_expense_item_fkey
        foreign key (expense_item_id) references expense_items (id) on delete cascade;
"""
DROP_KEYS = """
alter table classification_rules
    drop constraint if exists classification_rules_expense_item_fkey,
    drop constraint if exists classification_rules_counterparty_fkey;
"""

COMMENTS = """
comment on table classification_rules is
    'Память разбора: какую статью человек дал этому поставщику. Предлагается в инбоксе, но никогда не проставляется сама (issue #173)';
comment on column classification_rules.hits is
    'Сколько раз человек подтвердил это соответствие: по нему видно, какая подсказка заслужена практикой, а какая поставлена одним разбором';
"""

POLICIES = """
alter table classification_rules enable row level security;
alter table classification_rules force  row level security;

create policy tenant_isolation on classification_rules
    for all
    using (tenant_id in (select app_tenant_ids()))
    with check (tenant_id in (select app_tenant_ids()));

create policy classify_insert on classification_rules
    as restrictive for insert
    with check (app_has_permission(tenant_id, 'suppliers.classify'));

create policy classify_update on classification_rules
    as restrictive for update
    with check (app_has_permission(tenant_id, 'suppliers.classify'));
"""

DROP_POLICIES = """
drop policy if exists classify_update on classification_rules;
drop policy if exists classify_insert on classification_rules;
drop policy if exists tenant_isolation on classification_rules;
alter table classification_rules no force row level security;
alter table classification_rules disable row level security;
"""

PRIVILEGES = """
grant select, insert, update, delete on classification_rules to app_user;
"""
DROP_PRIVILEGES = """
revoke all on classification_rules from app_user;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0254_reconciliation_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('hits', models.IntegerField(db_default=1)),
                ('decided_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(db_column='counterparty_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.counterparty')),
                ('expense_item', models.ForeignKey(db_column='expense_item_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.expenseitem')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'classification_rules',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'counterparty'), name='classification_rules_party_uniq')],
            },
        ),
        migrations.RunSQL(KEYS, DROP_KEYS),
        migrations.RunSQL(COMMENTS, migrations.RunSQL.noop),
        migrations.RunSQL(POLICIES, DROP_POLICIES),
        migrations.RunSQL(PRIVILEGES, DROP_PRIVILEGES),
    ]
