"""Накладная разносится по точкам руками, а не только правилом (issue #174).

Модуль 15 эталона отвечает на вопрос «чья накладная»: сумма раскладывается между
точками — по выручке, поровну или долями, которые человек поставил сам. Правилом
такое не выражается: правило говорит «этот поставщик всегда делится так-то», а
одна поставка сырья на две пиццерии — это не «всегда», это конкретная бумага.

**Что меняется в схеме.** У ребёнка разнесения было обязательно правило
(`facts_allocated_is_complete`). Теперь обязательно **одно из двух**: правило или
человек. Ослабления здесь нет — доля по-прежнему обязана откуда-то следовать, и
ограничение продолжает это требовать; появился второй законный источник.

**Функция разнесения руками — в базе, рядом с `allocate_fact`.** Копейки
раскладываются тем же приёмом, что и там (округление накопленной суммы и разность
с предыдущей), поэтому дети складываются в родителя до копейки, а остаток ложится
детерминированно, а не по порядку строк. Два разных способа деления одной суммы
разошлись бы на первой же неровной накладной.
"""

# Generated by Django 6.1 on 2026-08-27 23:42

from django.db import migrations, models

# Ограничение переписывается целиком: `alter ... drop constraint` + `add` —
# единственный способ изменить check в Postgres, менять его на месте нельзя.
CONSTRAINT = """
alter table facts
    drop constraint facts_allocated_is_complete,
    add constraint facts_allocated_is_complete
        check (allocation <> 'allocated'
               or (unit_id is not null and parent_fact_id is not null
                   and (allocation_rule_id is not null or allocated_by is not null)));
"""
CONSTRAINT_BACK = """
alter table facts
    drop constraint facts_allocated_is_complete,
    add constraint facts_allocated_is_complete
        check (allocation <> 'allocated'
               or (unit_id is not null and parent_fact_id is not null
                   and allocation_rule_id is not null));
"""

COMMENTS = """
comment on column facts.allocated_by is
    'Кто разнёс руками. Пусто — разнесло правило: тогда объяснение доли лежит в allocation_rule_id (issue #174)';
"""

# Разнести факт руками по долям. Живёт в базе, а не в Python, по той же причине,
# что и `allocate_fact`: разнесение — это запись набора строк, которые обязаны
# сойтись с родителем до копейки, и делать это двумя разными способами в двух
# местах значит однажды разойтись на неровной сумме.
#
# Доли приходят как {unit_id: доля}. Сумма долей проверяется вызывающим: здесь
# она нормируется (делится на свою сумму), потому что функция обязана быть
# честной и при 100, и при 1.0, и при 3 равных третях.
SPLIT_BY_HAND = """
create or replace function split_fact_by_hand(p_fact_id uuid, p_shares jsonb, p_actor uuid)
returns int
language plpgsql
as $$
declare
    f facts;
    p record;
    v_unit_code text;
    n int := 0;
begin
    select * into f from facts where id = p_fact_id and superseded_at is null;
    if not found then
        raise exception 'факт % не найден или уже заменён', p_fact_id;
    end if;
    if f.allocation <> 'pending' then
        return 0;    -- уже разнесён или разносить нечего
    end if;

    for p in
        with given as (
            select (key)::uuid as unit_id, (value)::text::numeric as weight
              from jsonb_each_text(p_shares)
        ),
        kept as (
            select g.unit_id, g.weight, u.code as unit_code
              from given g
              join units u on u.id = g.unit_id
             where g.weight > 0
               and u.tenant_id = f.tenant_id
               -- Фактура пришла на юрлицо — разносится только на его точки.
               -- Та же проверка, что в `allocation_plan`: разнести на чужое
               -- юрлицо значит переложить расход между компаниями молча.
               and (f.legal_entity_id is null or u.legal_entity_id = f.legal_entity_id)
        ),
        ordered as (
            select k.unit_id, k.unit_code, k.weight,
                   sum(k.weight) over (order by k.unit_code
                                       rows between unbounded preceding and current row) as cum,
                   sum(k.weight) over () as total
              from kept k
        )
        select o.unit_id, o.unit_code,
               round(o.weight / o.total, 6) as share,
               round(f.amount * o.cum / o.total, 2)
                   - round(f.amount * (o.cum - o.weight) / o.total, 2) as amount,
               case when f.amount_report is null then null
                    else round(f.amount_report * o.cum / o.total, 2)
                         - round(f.amount_report * (o.cum - o.weight) / o.total, 2)
               end as amount_report
          from ordered o
         where o.total > 0
    loop
        perform upsert_fact(jsonb_build_object(
            'tenant_id',          f.tenant_id,
            'period',             f.period,
            'doc_date',           f.doc_date,
            'unit_id',            p.unit_id,
            'legal_entity_id',    f.legal_entity_id,
            'pnl_item_id',        f.pnl_item_id,
            'expense_item_id',    f.expense_item_id,
            'ledger',             f.ledger,
            'counterparty_id',    f.counterparty_id,
            'amount',             p.amount,
            'currency',           f.currency,
            'amount_report',      p.amount_report,
            'report_currency',    f.report_currency,
            'fx_rate',            f.fx_rate,
            'fx_rate_date',       f.fx_rate_date,
            'title',              f.title,
            'channel',            f.channel,
            'source',             f.source,
            'source_ref',         f.source_ref,
            'document_id',        f.document_id,
            'line_no',            f.line_no,
            'batch_id',           f.batch_id,
            'dedup_key',          f.dedup_key || '#' || p.unit_code,
            'allocation',         'allocated',
            'allocation_share',   p.share,
            'allocated_by',       p_actor,
            'parent_fact_id',     f.id
        ));
        n := n + 1;
    end loop;

    if n > 0 then
        update facts set allocation = 'split' where id = f.id;
    end if;

    return n;
end $$;

comment on function split_fact_by_hand(uuid, jsonb, uuid) is
    'Разнести ожидающий факт по точкам долями, которые дал человек (issue #174). Родитель становится split';
"""
DROP_SPLIT = "drop function if exists split_fact_by_hand(uuid, jsonb, uuid);"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_classification_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='allocated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL(CONSTRAINT, CONSTRAINT_BACK),
        migrations.RunSQL(COMMENTS, migrations.RunSQL.noop),
        migrations.RunSQL(SPLIT_BY_HAND, DROP_SPLIT),
    ]
