"""Бумага, признанная чужой: «не наша» (issue #174, T205).

Модуль 15 эталона ставит рядом с разбором кнопку «Не наша»: документ чужого
юрлица, ошибка почты поставщика, накладная соседнего арендатора. Без неё такую
бумагу приходится либо разбирать как свою — и она навсегда остаётся в P&L
неверной суммой, — либо оставлять в очереди, которая тогда перестаёт быть
рабочим списком.

**Пометка, а не удаление.** Удалённый документ через месяц принесут второй раз и
разберут как новый, а объяснить, почему его нет, будет нечем. Остаётся след: кто
решил, когда и почему.

**Причина обязательна на уровне схемы.** «Не наша» без слов через полгода не
отличить от «не разбирались» — тот же довод, что у решения по расхождению сверки
(`reconciliation_findings_note_with_decision`, миграция `0254`).
"""

# Generated by Django 6.1 on 2026-08-28 00:54

from django.db import migrations, models

COMMENTS = """
comment on column source_documents.not_ours_at is
    'Когда бумагу признали чужой. Пусто — обычный документ (issue #174)';
comment on column source_documents.not_ours_why is
    'Почему чужая. Обязательна: «не наша» без слов через полгода не отличить от «не разбирались»';
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0256_split_by_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='not_ours_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='not_ours_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='not_ours_why',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.CheckConstraint(condition=models.Q(('not_ours_at__isnull', True), ('not_ours_why__regex', '\\S'), _connector='OR'), name='source_documents_not_ours_has_a_reason'),
        ),
        migrations.RunSQL(COMMENTS, migrations.RunSQL.noop),
    ]
