"""Точки, на которых работает человек: затраты делятся, а не падают на одну (D055).

Решение владельца 27.08.2026: «управляющий может быть на несколько пиццерий
один… чтобы условный человек в Нови-Саде делился только по пиццериям Нови-Сада,
а в Белграде только на Белград». И про офис: «равномерно должно, потому что офис
на всех работает, вне зависимости».

До этого у ведомости была одна точка, и перенос зарплаты в P&L (issue #201) клал
весь ФОТ человека на неё. Для пиццамейкера это правда, для управляющего двумя
точками — нет: его зарплата целиком ложилась в затраты одной пиццерии, и её P&L
выглядел хуже соседнего без всякой причины.

**Версионируется по датам**, как всё, что влияет на закрытый месяц (D020):
перевод человека в сентябре не должен менять июньский P&L.
"""

# Generated by Django 6.1 on 2026-08-28 07:22

import django.db.models.deletion
from django.db import migrations, models

COMMENTS = """
comment on table employee_units is
    'Точки, на которых работает человек. Пусто — офис: деньги идут на разнесение общим правилом (D055)';
comment on column employee_units.share is
    'Доля точки. Пусто — поровну со всеми остальными: умолчание названо владельцем прямо';
"""

POLICIES = """
alter table employee_units enable row level security;
alter table employee_units force  row level security;

create policy tenant_isolation on employee_units
    for all
    using (tenant_id in (select app_tenant_ids()))
    with check (tenant_id in (select app_tenant_ids()));

create policy directory_write on employee_units
    as restrictive for insert
    with check (app_has_permission(tenant_id, 'directory.manage'));

create policy directory_update on employee_units
    as restrictive for update
    with check (app_has_permission(tenant_id, 'directory.manage'));

create policy directory_delete on employee_units
    as restrictive for delete
    using (app_has_permission(tenant_id, 'directory.manage'));
"""

DROP_POLICIES = """
drop policy if exists directory_delete on employee_units;
drop policy if exists directory_update on employee_units;
drop policy if exists directory_write on employee_units;
drop policy if exists tenant_isolation on employee_units;
alter table employee_units no force row level security;
alter table employee_units disable row level security;
"""

PRIVILEGES = "grant select, insert, update, delete on employee_units to app_user;"
DROP_PRIVILEGES = "revoke all on employee_units from app_user;"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_not_ours'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUnit',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('share', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.employee')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
            options={
                'db_table': 'employee_units',
                'indexes': [models.Index(models.F('tenant'), models.F('employee'), name='employee_units_person')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'unit', 'valid_from'), name='employee_units_no_repeat')],
            },
        ),
        migrations.RunSQL(COMMENTS, migrations.RunSQL.noop),
        migrations.RunSQL(POLICIES, DROP_POLICIES),
        migrations.RunSQL(PRIVILEGES, DROP_PRIVILEGES),
    ]
