"""Именованные надбавки человека: не спрятанные в коэффициент (issue #189, T196).

В условиях найма был один множитель, `coefficient`. Всё, чем на практике
отличается оплата человека — наставничество, старшинство, надбавка за точку, —
приходилось зашивать в него. Через полгода никто не мог сказать, почему у
человека 1,15 вместо 1,0, а снятие надбавки означало новую версию всей записи
найма вместе со ставкой, группой и точкой.

Эталон (модуль 16) держит те же надбавки в шаблоне должности: «Наставничество —
часы наставника × 30,00, дополнительный регистр». Отсюда состав таблицы: код,
название, величина, способ начисления, **свой регистр** и срок действия.

Регистр именно свой: в эталоне у одного человека наставничество лежит в
дополнительном, а ночные — в официальном. Взять регистр у условий найма значило
бы запретить эту пару, а она обычная.
"""

# Generated by Django 6.1 on 2026-09-02 14:44

import django.db.models.deletion
from django.db import migrations, models

import core.fields

COMMENTS = """
comment on table employee_allowances is
    'Именованные надбавки человека: наставничество, старшинство, надбавка за точку. Живут своими датами, чтобы снятие не заводило новую версию условий найма (issue #189)';
comment on column employee_allowances.basis is
    'per_hour — за отработанный час, per_month — суммой за месяц с пропорцией, percent — процентом к начислениям';
comment on column employee_allowances.ledger is
    'Регистр надбавки, а не человека: у одного человека наставничество бывает в дополнительном, а ночные в официальном';
comment on column employee_allowances.title is
    'Снимок названия на момент записи: закрытый месяц обязан выглядеть так, как в день закрытия';
"""

POLICIES = """
alter table employee_allowances enable row level security;
alter table employee_allowances force  row level security;

create policy tenant_isolation on employee_allowances
    for all
    using (tenant_id in (select app_tenant_ids()))
    with check (tenant_id in (select app_tenant_ids()));

-- Видимость по регистру: надбавка внутреннего регистра не должна быть видна
-- роли, которой внутренний регистр не отдан. Иначе сумма скрытого регистра
-- утекает названием строки — тот же класс, что D023.
create policy ledger_visibility on employee_allowances
    as restrictive for select
    using (ledger = any (app_visible_ledgers(tenant_id)));

create policy directory_write on employee_allowances
    as restrictive for insert
    with check (app_has_permission(tenant_id, 'directory.manage'));

create policy directory_update on employee_allowances
    as restrictive for update
    with check (app_has_permission(tenant_id, 'directory.manage'));

create policy directory_delete on employee_allowances
    as restrictive for delete
    using (app_has_permission(tenant_id, 'directory.manage'));
"""

DROP_POLICIES = """
drop policy if exists directory_delete on employee_allowances;
drop policy if exists directory_update on employee_allowances;
drop policy if exists directory_write on employee_allowances;
drop policy if exists ledger_visibility on employee_allowances;
drop policy if exists tenant_isolation on employee_allowances;
alter table employee_allowances no force row level security;
alter table employee_allowances disable row level security;
"""

PRIVILEGES = "grant select, insert, update, delete on employee_allowances to app_user;"
DROP_PRIVILEGES = "revoke all on employee_allowances from app_user;"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0261_platform_admin_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafeed',
            name='id',
            field=models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('basis', models.TextField(db_default='per_month')),
                ('ledger', core.fields.EnumField(db_default='official', db_type_name='ledger')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='core.employee')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'employee_allowances',
                'indexes': [models.Index(models.F('tenant'), models.F('employee'), name='employee_allowances_person')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'code', 'valid_from'), name='employee_allowances_no_repeat'), models.CheckConstraint(condition=models.Q(('basis__in', ['per_hour', 'per_month', 'percent'])), name='employee_allowances_known_basis'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='employee_allowances_dates_in_order')],
            },
        ),
        migrations.RunSQL(COMMENTS, migrations.RunSQL.noop),
        migrations.RunSQL(POLICIES, DROP_POLICIES),
        migrations.RunSQL(PRIVILEGES, DROP_PRIVILEGES),
    ]
