"""Точки человека доходят до экрана: непересечение версий и срез по точкам (T210).

`0258` завела саму связь «человек → точки» (D055) и закрыла её от чужих рук
правом `directory.manage`. Экрана у неё не было, писал в неё только SQL — и двух
вещей, которые нужны экрану, там поэтому не оказалось.

**Первое: версии одной точки не должны пересекаться.** Уникальность
`employee_units_no_repeat` ловит только повтор с той же датой начала. Порчу
денег даёт другое: `payrun.posting._units_of` берёт все действующие строки
списком, и каждая идёт отдельным весом. Две пересекающиеся строки одной точки
— двойной вес, то есть чужая доля ФОТ у соседней пиццерии. Экран такого набрать
не даст (он закрывает прежние версии, а не кладёт вторую поверх), но гарантия
обязана стоять на данных, а не на том, что единственный путь записи вежлив.

**Второе: у строки есть точка, а среза по точкам на таблице не было.** Правило
видимости точки живёт в одном месте — `app_unit_is_visible()` (`0011`), — и все
таблицы, где точка означает принадлежность строки, им закрыты: условия найма,
табели, ведомости. `employee_units` в тот список не попала: пока в неё писал
только SQL, читать её было некому, и промах ничего не значил. С появлением блока
в карточке сотрудника он начинает значить: управляющий точки читает карточки
своих людей (T173) и увидел бы, на каких ЕЩЁ точках человек работает, — то есть
узнал бы о существовании точек, которых ему не видно (D023).

Политика `as restrictive`, как и все сужающие: разрешающие Postgres объединяет
через ИЛИ, и «сужающая», добавленная разрешающей, не сужает ничего. И `for all`,
а не `for select`: иначе управляющий чужую точку не видел бы, но мог бы в неё
записать — привязать своего человека к пиццерии, о которой не должен знать.

Расчёту это ничего не ломает: точки не ограничены у тех, кто считает период
целиком (бухгалтер, директор, администратор), а перенос ФОТ в факты идёт при
утверждении расчёта — то есть их руками.
"""

# Generated by Django 6.1 on 2026-09-02 22:44

import django.contrib.postgres.constraints
from django.db import migrations, models

import core.models

# Срез по точкам — тем же единственным правилом, что и у остальных таблиц с
# точкой (`app_unit_is_visible`, `0011`). Условие не переписывается здесь
# руками нарочно: разъехавшиеся копии одного правила доступа и есть тот способ,
# которым он ломается незаметно.
POLICY = """
create policy unit_visibility on employee_units
    as restrictive for all
    using (app_unit_is_visible(tenant_id, unit_id))
    with check (app_unit_is_visible(tenant_id, unit_id));
"""

DROP_POLICY = "drop policy if exists unit_visibility on employee_units;"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_unit_move_guard'),
    ]

    operations = [
        migrations.RunSQL(POLICY, DROP_POLICY),
        migrations.AddConstraint(
            model_name='employeeunit',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('employee', '='), ('unit', '='), (core.models.DateRange('valid_from', 'valid_to', models.Value('[)')), '&&')], name='employee_units_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='employeeunit',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='employee_units_dates_in_order'),
        ),
    ]
